Skarlso/crd-to-sample-yaml

README.md
Thanks for providing me with instructions @Skarlso on Discord on how to get started! I thought I'll add them quickly to the Readme 😊
=> Add instructions on how to get started

pkg/templates/index.html
Fixes #12 
- Fixed color of the Navbar title
- Fixed GitHub icon size and color
- Fixed margin in between button and textarea
@Skarlso Kindly review and add hacktoberfest-label to this PR
=> Updated styling

pkg/templates/index.html
Sorry the previous PR was not with respect to the updated repository also had false merge conflicts resolved by mistake
=> Updated navbar

cmd/generate.go, pkg/generate.go, sample-crd/awsclusters.infrastructure.cluster.x-k8s.io_sample.yaml, wasm/app-worker.js, wasm/app.go, wasm/app.js, wasm/index.go, wasm/index.html
=> feat: optionally generate comments in the sample file for all fields

wasm/app-worker.js, wasm/app.go, wasm/app.js, wasm/index.html, wasm/main.go
=> add diff to none empty nodes

docs/release_notes/v0.3.3.md, pkg/generate.go, pkg/generate_test.go, pkg/testdata/sample_crd_with_example.yaml, pkg/testdata/sample_crd_with_example_golden.yaml, wasm/app-worker.js, wasm/app.go, wasm/app.js, wasm/index.html
=> add using example after default if it is defined

README.md, cmd/generate.go, pkg/create_html_output.go, pkg/generate.go, pkg/generate_test.go, pkg/testdata/sample_crd_with_comments_golden.yaml, pkg/testdata/sample_crd_with_minimal_example_golden.yaml, pkg/testdata/sample_crd_with_minimal_example_with_example_for_field_golden.yaml, sample-crd/awsclusters.infrastructure.cluster.x-k8s.io_sample.html, sample-crd/krokcommands.delivery.krok.app_sample.html, wasm/app-worker.js, wasm/app.go, wasm/app.js, wasm/index.html
Closes https://github.com/Skarlso/crd-to-sample-yaml/issues/70
=> feat: add minimal working example using required fields only

.golangci.yaml, README.md, cmd/file_handler.go, cmd/folder_handler.go, cmd/url_handler.go, go.mod, pkg/sanitize/sanitizer.go, pkg/sanitize/sanitizer_test.go, sample-crd/HelmRelease_crd_with_template.yaml, wasm/index.html, wasm/share.html
Fixes https://github.com/Skarlso/crd-to-sample-yaml/issues/84
=> feat: sanitize templated helm CRDs

cmd/generate.go, cmd/url_handler.go, pkg/fetcher/fetch_content.go, wasm/app.go, wasm/index.go, wasm/index.html, wasm/share.html
=> feat: add url authentication

cmd/file_handler.go, cmd/folder_handler.go, cmd/generate.go, cmd/url_handler.go, pkg/create_html_output.go, pkg/generate.go, pkg/generate_test.go, pkg/matches/matchsnapshot/update.go, wasm/app.go
CustomerResourceDefinitions since a while available in v1 so update all v1beta1 deps to v1 
executed a bunch of tests
=> feat(bump): use in codebase v1.CustomResourceDefinition

gotemplates.gotemplating.fn.crossplane.io_sample.yaml, pkg/generate_test.go, pkg/sanitize/sanitizer.go, pkg/sanitize/sanitizer_test.go, pkg/testdata/sample_crd_with_template_start_character_default_value.yaml, pkg/testdata/sample_crd_with_template_start_character_default_value_golden.yaml
Closes https://github.com/Skarlso/crd-to-sample-yaml/issues/103
=> fix: do not skip lines that do not have closing brackets

.golangci.yaml, pkg/create_html_output.go, pkg/generate.go, pkg/generate_test.go, pkg/matches/matchsnapshot/update.go, pkg/testdata/sample_crd_minimal_no_required_fields.yaml, pkg/testdata/sample_crd_minimal_no_required_fields_golden.yaml, pkg/testdata/sample_crd_with_minimal_example_golden.yaml, pkg/testdata/sample_crd_with_minimal_example_with_example_for_field_golden.yaml, sample-tests/__snapshots__/bootstrap_crd-v1alpha1.min.yaml, sample-tests/__snapshots__/bootstrap_crd-v1alpha1.yaml, sample-tests/__snapshots__/infrastructure.cluster.x-k8s.io_awsclusters-v1beta1.min.yaml, sample-tests/__snapshots__/infrastructure.cluster.x-k8s.io_awsclusters-v1beta1.yaml, sample-tests/__snapshots__/infrastructure.cluster.x-k8s.io_awsclusters-v1beta2.min.yaml, sample-tests/__snapshots__/infrastructure.cluster.x-k8s.io_awsclusters-v1beta2.yaml, wasm/app.go, wasm/index.html, wasm/share.html
Closes https://github.com/Skarlso/crd-to-sample-yaml/issues/104
Note that one of the tests will still fail because it's intended to fail to show that it can. But the rest will properly update now using the `--update` flag.
=> fix: properly render required fields and empty object bodies

wasm/app.go, wasm/index.go, wasm/index.html, wasm/share.html
Closes https://github.com/Skarlso/crd-to-sample-yaml/issues/81
=> added a true navigate back button that properly clears the content and is smoother expercience

.github/workflows/test.yaml, cmd/file_handler.go, cmd/folder_handler.go, cmd/generate.go, cmd/url_handler.go, pkg/create_html_output.go, pkg/generate.go, pkg/generate_test.go, pkg/matches/matchsnapshot/update.go, pkg/matches/validate.go, pkg/testdata/sample_crd_with_list_and_multiple_versions.yaml, pkg/testdata/sample_crd_with_list_and_multiple_versions_golden.yaml, pkg/testdata/sample_crd_with_validation.yaml, pkg/testdata/sample_crd_with_validation_golden.yaml, sample-crd/prometheus.crd.yaml, sample-tests/__snapshots__/bootstrap_crd-v1alpha1.yaml, sample-tests/__snapshots__/infrastructure.cluster.x-k8s.io_awsclusters-v1beta1.yaml, sample-tests/__snapshots__/infrastructure.cluster.x-k8s.io_awsclusters-v1beta2.yaml, sample-tests/__snapshots__/prometheus.crd-prometheuses.monitoring.coreos.com.min.yaml, sample-tests/__snapshots__/prometheus.crd-prometheuses.monitoring.coreos.com.yaml, sample-tests/awsclusters_test.yaml, sample-tests/crds/prometheus.crd.yaml, sample-tests/prometheus_test.yaml, wasm/app-worker.js, wasm/app.go, wasm/app.js, wasm/index.go, wasm/index.html, wasm/share.html
Closes https://github.com/Skarlso/crd-to-sample-yaml/issues/114
=> fix: support v1beta2 for CRD and fix indentation and a few minor changes

.github/workflows/sync_jsonschema.yaml, .golangci.yaml, README.md, cmd/crd.go, cmd/file_handler.go, cmd/folder_handler.go, cmd/schema.go, cmd/url_handler.go, docs/release_notes/v1.0.0.md, go.mod, hack/keep_json_schema_uptodate.sh, pkg/README.md, pkg/create_html_output.go, pkg/extract_schematype.go, pkg/extract_schematype_test.go, pkg/generate.go, pkg/generate_test.go, pkg/marshal.go, pkg/marshal_test.go, pkg/matches/matchsnapshot/update.go, pkg/schema_type.go, pkg/testdata/sample_crd_different_crd_type.yaml, pkg/testdata/sample_crd_different_crd_type_golden.yaml, pkg/types_jsonschema.go, wasm/app.go, wasm/index.go, wasm/index.html, wasm/share.html
Closes https://github.com/Skarlso/crd-to-sample-yaml/issues/117
=> feat: add generating samples for any kind of object that supports openAPIV3schema

cmd/crd.go, docs/release_notes/v1.0.1.md, pkg/create_html_output.go
Closes https://github.com/Skarlso/crd-to-sample-yaml/issues/124
=> fix: use the random flag in create html output

index.html, pkg/create_html_output.go, sample-crd/infrastructure.cluster.x-k8s.io_awsclusters.yaml
Closes https://github.com/Skarlso/crd-to-sample-yaml/issues/123
=> feat: adding apiVersion and kind value if description is empty

pkg/create_html_output.go, pkg/generate.go, pkg/templates/view_with_groups.html, pkg/testdata/sample_crd_different_crd_type_golden.yaml, pkg/testdata/sample_crd_golden.yaml, pkg/testdata/sample_crd_with_comments_golden.yaml, pkg/testdata/sample_crd_with_list_and_multiple_versions_golden.yaml, sample-crd/crd_with_enum.yaml
Closes https://github.com/Skarlso/crd-to-sample-yaml/issues/138
=> feat: add dislpaying enum values as a list

pkg/create_html_output.go
Closes https://github.com/Skarlso/crd-to-sample-yaml/issues/146.
=> fix: additional properties schema being nil for create html output

pkg/create_html_output.go, pkg/generate_test.go, pkg/testdata/sample_crd_with_additional_properties_and_properties.yaml, pkg/testdata/sample_crd_with_additional_properties_and_properties_golden.yaml, wasm/app.go, wasm/index.html, wasm/manifest.webmanifest, wasm/share.html
=> fix: fixing checking additional property when it is not required

pkg/create_html_output.go, pkg/generate.go, pkg/generate_test.go, pkg/matches/matchsnapshot/update.go, pkg/testdata/sample_crd_minimal_with_embedded_object.yaml, pkg/testdata/sample_crd_minimal_with_embedded_object_golden.yaml, wasm/app-worker.js, wasm/app.go, wasm/index.go, wasm/index.html, wasm/main.go, wasm/share.html, wasm/web/css/yaml.css
Closes https://github.com/Skarlso/crd-to-sample-yaml/issues/127
=> feat: add option to generate Details section on the spot

cmd/crd.go, cmd/generate.go, cmd/stdin_handler.go
Towards https://github.com/Skarlso/crd-to-sample-yaml/issues/171
=> feat: add reading crds from stdin

README.md, cmd/crd.go, cmd/generate.go, cmd/kube_handler.go, go.mod
Closes https://github.com/Skarlso/crd-to-sample-yaml/issues/171
=> feat: add kubernetes cluster access and listing crds in the cluster

wasm/app.go, wasm/index.go
Closes https://github.com/Skarlso/crd-to-sample-yaml/issues/213
=> feat: add share link once URL is used

pkg/templates/view_with_groups.html
Fix https://github.com/Skarlso/crd-to-sample-yaml/issues/220. Again...
=> fix: put examples generation back into html view

README.md, cmd/crd.go, pkg/create_html_output.go, pkg/sanitize_css.go, pkg/sanitize_css_test.go, pkg/templates/view_with_groups.html, pkg/test-custom.css
Closes https://github.com/Skarlso/crd-to-sample-yaml/issues/98
=> feat: add ability to inject custom CSS into HTML output

.goreleaser.yml
Related to https://github.com/Skarlso/crd-to-sample-yaml/issues/252
=> chore: add krew settings for go releaser
